Repository ColoredCow/goonj, pull requests merged in 2024-10, with the labels that each got.

#298 Add cc and address for diapatch, outcome and feedback form
  wp-content/civi-extensions/goonjcustom/api/v3/Goonjcustom/CollectionCampCron.php
Labels: in review

#274 Change mmt to frontend
  wp-content/civi-extensions/goonjcustom/Civi/CollectionCampService.php
  wp-content/themes/goonj-crm/style.css
Labels: in review

#301 Remove the filled by option for ACK form
  wp-content/civi-extensions/goonjcustom/Civi/CollectionCampService.php
Labels: in review

#313 Fix the sharable link
  wp-content/civi-extensions/goonjcustom/CRM/Goonjcustom/Form/CollectionCampLinks.php
  wp-content/civi-extensions/goonjcustom/Civi/CollectionCampService.php
  wp-content/civi-extensions/goonjcustom/api/v3/Goonjcustom/CollectionCampCron.php
Labels: in review

#316 Add the params on API to get contact id
  wp-content/civi-extensions/goonjcustom/api/v3/Goonjcustom/CollectionCampCron.php
Labels: in review

#319 Change the type of custom field
  wp-content/civi-extensions/goonjcustom/CRM/Goonjcustom/Form/CollectionCampLinks.php
  wp-content/civi-extensions/goonjcustom/Civi/CollectionCampService.php
  wp-content/civi-extensions/goonjcustom/api/v3/Goonjcustom/CollectionCampCron.php
Labels: in review

#318 Send an email on the start date of the camp
  wp-content/civi-extensions/goonjcustom/api/v3/Goonjcustom/CollectionCampCron.php
Labels: in review

#320 Add the Update Scheduled Time Job
  wp-content/civi-extensions/goonjcustom/Civi/CollectionCampService.php
  wp-content/civi-extensions/goonjcustom/api/v3/Goonjcustom/UpdateScheduledTimeCron.php
Labels: in review

#324 Add CC recipient to contribution receipt email
  wp-content/civi-extensions/goonjcustom/Civi/MaterialContributionService.php
Labels: in review

#338 Refactor: Dropping Center Tabs
  wp-content/civi-extensions/goonjcustom/Civi/DroppingCenterService.php
Labels: in review

#341 Fix the autofilling of collection camp when someone has filled it already
  wp-content/themes/goonj-crm/functions.php
Labels: in review

#346 Add state and city in params for individual registration
  wp-content/plugins/goonj-blocks/build/render.php
  wp-content/plugins/goonj-blocks/goonj-blocks.php
  wp-content/plugins/goonj-blocks/src/render.php
  wp-content/themes/goonj-crm/functions.php
  wp-content/themes/goonj-crm/templates/form-check-user.php
Labels: status : ready for review

#355 Removed Custom Validation
  wp-content/civi-extensions/goonjcustom/Civi/GoonjUniqueUserValidation.php
Labels: status : ready for review

#350 Added time row for collection camp
  wp-content/plugins/goonj-blocks/build/functions.php
  wp-content/plugins/goonj-blocks/build/render.php
  wp-content/plugins/goonj-blocks/src/functions.php
  wp-content/plugins/goonj-blocks/src/render.php
Labels: status : ready for review

#352 Refactor `CollectionCampService.php` and `DroppingCenterService.php`
  wp-content/civi-extensions/goonjcustom/Civi/CollectionCampService.php
  wp-content/civi-extensions/goonjcustom/Civi/DroppingCenterService.php
  wp-content/civi-extensions/goonjcustom/Civi/Traits/CollectionSource.php
  wp-content/civi-extensions/goonjcustom/Civi/Traits/QrCodeable.php
Labels: status : ready for review

#349 Volunteer camp feedback reminder
  wp-content/civi-extensions/goonjcustom/Civi/CollectionCampVolunteerFeedbackService.php
  wp-content/civi-extensions/goonjcustom/Civi/HelperService.php
  wp-content/civi-extensions/goonjcustom/api/v3/Goonjcustom/VolunteerFeedbackReminderCron.php
Labels: status : reviewed

#343 Collection camp outcome reminder
  wp-content/civi-extensions/goonjcustom/Civi/CollectionCampOutcomeService.php
  wp-content/civi-extensions/goonjcustom/api/v3/Goonjcustom/CollectionCampOutcomeReminderCron.php
Labels: status : ready for review

#366 Fix the condition for Camp outcome reminder
  wp-content/civi-extensions/goonjcustom/Civi/CollectionCampOutcomeService.php
Labels: status : ready for review

#364 Refactor date and address handling logic for collection camps and dropping centers
  wp-content/plugins/goonj-blocks/build/render.php
  wp-content/plugins/goonj-blocks/goonj-blocks.php
  wp-content/plugins/goonj-blocks/src/render.php
Labels: status : ready for review

#365 Dropping Center Material Contribution Workflow
  wp-content/civi-extensions/goonjcustom/Civi/CollectionBaseService.php
  wp-content/civi-extensions/goonjcustom/Civi/CollectionCampService.php
  wp-content/civi-extensions/goonjcustom/Civi/DroppingCenterService.php
  wp-content/themes/goonj-crm/functions.php
  wp-content/themes/goonj-crm/templates/form-check-user.php
Labels: status : reviewed

#266 Feat/dropping center dispatch email
  wp-content/civi-extensions/goonjcustom/Civi/CollectionCampService.php
  wp-content/civi-extensions/goonjcustom/Civi/DroppingCenterService.php
Labels: status : ready for review

#362 Collection Camp Authorisation Status
  wp-content/civi-extensions/goonjcustom/Civi/CollectionCampService.php
  wp-content/civi-extensions/goonjcustom/api/v3/Goonjcustom/CollectionCampCron.php
  wp-content/civi-extensions/goonjcustom/api/v3/Goonjcustom/CollectionCampOutcomeReminderCron.php
  wp-content/civi-extensions/goonjcustom/api/v3/Goonjcustom/VolunteerFeedbackCollectionCampCron.php
  wp-content/civi-extensions/goonjcustom/api/v3/Goonjcustom/VolunteerFeedbackReminderCron.php
Labels: status : ready for review

#378 Update Volunteer Registration Or Dropping Center Case
  wp-content/themes/goonj-crm/functions.php
  wp-content/themes/goonj-crm/main.js
Labels: status : reviewed

#386 Add Validation to Prevent Selection of Past Dates in Dropping Center Form
  wp-content/plugins/civicrm/civicrm/ext/afform/core/ang/af/afForm.component.js
Labels: status : ready for review

#385 Optimize State Field for Dropping Center Form to Show Only Indian States
  wp-content/civi-extensions/goonjcustom/Civi/DroppingCenterService.php
Labels: status : ready for review

#387 update error message for center date validation
  wp-content/plugins/civicrm/civicrm/ext/afform/core/ang/af/afForm.component.js
Labels: status : ready for review

#377 Update Dropping Center Outcome Details via Daily Cron Job
  wp-content/civi-extensions/goonjcustom/api/v3/Goonjcustom/DroppingCenterOutcomeCron.php
Labels: status : ready for review

#384 Added additional params to auto fill form fields
  wp-content/themes/goonj-crm/engine/helpers.php
  wp-content/themes/goonj-crm/engine/shortcodes.php
Labels: status : ready for review

#373 Dropping Center Poster Implmentation
  wp-content/civi-extensions/goonjcustom/CRM/Goonjcustom/Token/DroppingCenter.php
  wp-content/civi-extensions/goonjcustom/Civi/CollectionBaseService.php
  wp-content/civi-extensions/goonjcustom/goonjcustom.php
Labels: status : ready for review

#388 Fix the status feedbacks
  wp-content/civi-extensions/goonjcustom/Civi/CollectionCampService.php
Labels: status : reviewed

#391 Add feedback tab for dropping center
  wp-content/civi-extensions/goonjcustom/Civi/DroppingCenterService.php
Labels: status : ready for review

#389 Add Event Coordinato tab for dropping center
  wp-content/civi-extensions/goonjcustom/Civi/CollectionBaseService.php
  wp-content/civi-extensions/goonjcustom/Civi/CollectionCampService.php
  wp-content/civi-extensions/goonjcustom/Civi/DroppingCenterService.php
Labels: status : ready for review

#392 Reminder for outcome 2 emails will be sent
  wp-content/civi-extensions/goonjcustom/Civi/CollectionCampOutcomeService.php
  wp-content/civi-extensions/goonjcustom/api/v3/Goonjcustom/CollectionCampOutcomeReminderCron.php
Labels: status : ready for review

#393 Send Feedback Email When Dropping Center is Closed or sent every 6 month
  wp-content/civi-extensions/goonjcustom/Civi/DroppingCenterFeedbackService.php
  wp-content/civi-extensions/goonjcustom/api/v3/Goonjcustom/BiannualDroppingCenterFeedbackCron.php
  wp-content/civi-extensions/goonjcustom/api/v3/Goonjcustom/FeedbackDroppingCenterCron.php
Labels: status : ready for review

#396 Fix Spelling
  wp-content/civi-extensions/goonjcustom/api/v3/Goonjcustom/BiannualDroppingCenterFeedbackCron.php
Labels: status : ready for review

#397 Dropping Center Feedback Cron Fixes
  wp-content/civi-extensions/goonjcustom/Civi/DroppingCenterFeedbackService.php
  wp-content/civi-extensions/goonjcustom/api/v3/Goonjcustom/BiannualDroppingCenterFeedbackCron.php
  wp-content/civi-extensions/goonjcustom/api/v3/Goonjcustom/FeedbackDroppingCenterCron.php
Labels: status : ready for review

#398 Update Content For Dropping Center Feedback Email
  wp-content/civi-extensions/goonjcustom/Civi/DroppingCenterFeedbackService.php
Labels: status : ready for review

#399 Do Not Send Feedback Emails for Closed Status in Biannual Cron
  wp-content/civi-extensions/goonjcustom/api/v3/Goonjcustom/BiannualDroppingCenterFeedbackCron.php
  wp-content/civi-extensions/goonjcustom/api/v3/Goonjcustom/FeedbackDroppingCenterCron.php
Labels: status : ready for review

#400 Resolve Dropping Center Feedbacks
  wp-content/civi-extensions/goonjcustom/Civi/DroppingCenterService.php
  wp-content/plugins/civicrm/civicrm/ext/afform/core/ang/af/afForm.component.js
  wp-content/themes/goonj-crm/functions.php
Labels: status : ready for review

#404 Add read-only custom field for displaying Goonj Office name in vehicle dispatch form
  wp-content/civi-extensions/goonjcustom/Civi/DroppingCenterService.php
Labels: status : ready for review
